name: Hexo CICD
on:
  push:
    branches:
    - master
jobs:
  deploy:
    name: hexo build & deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - uses: actions/setup-node@master
      with:
        node-version: 12.x         
    - name: Installation
      run: |
        npm install
        npm install -g hexo-cli gulp        
    - name: Generate
      run: hexo clean && hexo g && gulp && hexo d
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./public
        cname: yuwengeng.github.io
    - name: Create Release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ steps.replace.outputs.tagname }}
        release_name: ${{ steps.replace.outputs.tagname }}
        body: Automatic generated
        draft: false
        prerelease: true
